config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  resources :users do
     resource :relationships, only: [:create, :destroy]
     get :followings, on: :member
     get :followers, on: :member
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/serch.rb
class Serch < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end
  def is_followed_by?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!,except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?
 
  def after_sign_in_path_for(resource)
   user_path(resource)
  end
 
  protected
  
 def configure_permitted_parameters
    added_attrs = [:user_name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    book_comment = current_user.book_comments.new(book_comment_params)
    book_comment.book_id = book.id
    book_comment.save
    @comments = book.book_comments
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:body)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @favorite = Favorite.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
    @book_comments = BookComment.new
    @comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
     render "edit"
    else
      redirect_to books_path
    end
  end

 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
 end

 def destroy
   book = Book.find(params[:id])
   book.destroy
   redirect_to books_path
 end

 private
 def book_params
   params.require(:book).permit(:title, :body)
 end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
def top
  
end

def about
end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

private
  def search_for(model,content,method)
    if model == 'user'
      if method == "forward_match"
        User.where("name LIKE?", "#{content}%")
      elsif method == "backward_match"
        User.where("name LIKE?", "#{content}%")
      elsif method == "perfect_match"
        User.where("#{content}")
      elsif method == "partial_match"
        User.where("name LIKE?", "%#{content}%")
      else
        User.all
      end
    elsif model == 'book'
      if method == "forward_match"
        Book.where("name LIKE?", "#{content}%")
      elsif method == "backward_match"
        Book.where("name LIKE?", "#{content}%")
      elsif method == "perfect_match"
        Book.where("#{content}")
      elsif method == "partial_match"
        Book.where("name LIKE?", "%#{content}%")
      else
        Book.all
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
   @users = User.all
   @book = Book.new
   @follower_users = User.where.not(id: current_user.id)
   @user = current_user
  end

  def show
   @user = User.find(params[:id])
   @book = Book.new
  end

  def edit
      @user = User.find(params[:id])
   if @user == current_user
      render "edit"
   else
      redirect_to user_path(current_user)
   end
  end

  def update
   @user = User.find(params[:id])
   if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
   else
    render :edit
   end
  end

  def followings
   user = User.find(params[:id])
   @users = user.followings
  end

  def followers
   user = User.find(params[:id])
   @users = user.followers
  end

  private
  def user_params
   params. require(:user) .permit(:name, :email, :profile_image, :introduction)
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment-index.html.erb
<% comments.each do |book_comment| %>
 <tr>
   <td>
     <%= attachment_image_tag book_comment.user, :profile_image,:fill, 100, 100, format: 'jpeg', fallback: "no-image.png",size:'40x40', class:"attachment user profile_image fallback" %>
     <br></br>
     <%= book_comment.user.name %>
   </td>
   <td>
     <%= book_comment.body %>
   </td>
   <td>
     <% if book_comment.user == current_user %>
      <%= link_to"Destroy",book_book_comment_path(book_comment.book,book_comment), method: :delete, class:"btn-danger btn-sm" %>
     <% end %>
   </td>
 </tr>
<% end %>

app/views/book_comments/_comment.html.erb
<%= form_with model: [book, book_comments], remote:true do |f| %>
  <%= f.text_area :body,class:"form-control book_body" %>
  <%= f.submit '送信' %>
<% end %>

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= escape_javascript(render 'comment-index', comments: @comments) %>")
$("textarea").val('')

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Option</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td><%= attachment_image_tag @user, :profile_image,:fill, 100, 100, format:'jpg' , fallback: "no-image.png",size:'40x40', class:"attachment user profile_image fallback" %> <br></td>
      <td>
        <%= link_to book_path(book)  do %>
          <%= book.title %>
        <% end %>
      </td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_list.html.erb
 <h2>User info</h2>
 <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no-image.png", size:'100x100', class:"attachment user profile_image fallback" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to @user.followings.count,followings_user_path(@user) %></th>
      </tr>
      <tr>
        <th>follower</th>
        <th><%= link_to @user.followers.count,followers_user_path(@user)  %></th>
      </tr>
    </tbody>
  </table>
<% if @user == current_user %>
  <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block", method: :get do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<% else %>
  <div>
     <% if current_user.is_followed_by?(@user) %>
         <%= link_to user_relationships_path(@user), class: "btn btn-info", method: :delete do %>
             フォロー外す
         <% end %>
     <% else %>
          <%= link_to user_relationships_path(@user), class: "btn btn-success", method: :post do %>
             フォローする
         <% end %>
  <% end %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h2>
      <div id="error_explanation" class="text-danger">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
      </div>
      <%= form_with model:@book,local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
           <%= f.text_field :title,class:"form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Option</label>
          <%= f.text_area :body,class:"form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book",class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %>
       |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'searches/form' %>
    </div>
  </div>
</div>
<main>
  <div class="container px-5 px-sm-0">
    <div id="error_explanation" class="text-danger">
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', user: @user %>
        <h2 class="mt-3">New book</h2>
          <%= form_with model:@book,local:true do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class:"form-control book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Option</label>
              <%= f.text_area :body,class:"form-control book_body" %>
            </div>
            <div class="form-group">
              <%= f.submit "Create Book",class:"btn btn-success" %>
            </div>
          <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Option</th>
              <th colspan="3"></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image,:fill, 100, 100, format: 'jpeg', fallback: "no-image.png",size:'40x40', class:"attachment user profile_image fallback" %>
                  <% end %>
                </td>
                <td>
                   <%= link_to book_path(book) do %>
                     <%= book.title %>
                   <% end %>
                </td>
                <td><%= book.body %></td>
                <td>
                  <!--いいね部分-->
                  <%= render 'favorites/favorite-btn', book: book %>
                </td>
                <td>
                  <p>
                  コメント数:<%= book.book_comments.count %>
                  </p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
 <div class="container px-5 px-sm-0">
   <div class="row">
     <div class="col-md-3">
      <%= render 'books/list', user: @user %>
      <h2 class="mt-3">New book</h2>
        <%= form_with model:@books,local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control book_title" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Option</label>
            <%= f.text_area :body,class:"form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit "Create Book",class:"btn btn-success" %>
          </div>
        <% end %>
     </div>
     <div class="col-md-8 offset-md-1">
       <h2>Book detail</h2>
       <table class="table">
         <tbody>
           <tr>
             <td>
              <%= attachment_image_tag @user, :profile_image,:fill, 100, 100, format:'jpg' , fallback: "no-image.png",size:'40x40', class:"attachment user profile_image fallback" %> <br>
              <%= link_to user_path(@user) do %>
               <%= @user.name %>
              <% end %>
             </td>
             <td>
              <%= link_to book_path(@book) do %>
              <%= @book.title %>
              <% end %>
             </td>
             <td><%= @book.body %></td>
             <td id="#favorite_buttons_<%= @book.id %>">
                <%= render 'favorites/favorite-btn', book: @book %>
             </td>
             <td>
                <p>コメント数:<%= @book.book_comments.count %></p>
             </td>
             <% if @user.id ==  current_user.id %>
             <td><%= link_to "Edit", edit_book_path(@book),class:"btn btn-sm btn-success edit_book_20900" %></td>
             <td><%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger destroy_book_20900" %></td>
             <% end %>
           </tr>
         </tbody>
       </table>
       <table>
          <!--コメント一覧機能-->
          <tbody id="comments_area" >
              <%= render 'book_comments/comment-index', comments: @comments %>
           </tbody>
       </table>
       <table class="table">
            <tbody>
              <tr>
                <%= render 'book_comments/comment',book: @book, book_comments: @book_comments %>
               </tr>
           </tbody>
          </table>
      </div>
     </div>
   </div>
 </div>

app/views/favorites/_favorite-btn.html.erb
<% if current_user.already_favorited?(book) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart heart_red"></i>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% end %>

<%= @book.favorites.count %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite-btn", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite-btn", book: @book) %>");

app/views/users/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag @user, :profile_image,:fill, 100, 100, format:'jpg' , fallback: "no-image.png",size:'40x40', class:"attachment user profile_image fallback" %> <br></td>
      <td><%= user.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>
      <div id="error_explanation" class="text-danger">
        <% if @user.errors.any? %>
         <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <% @user.errors.full_messages.each do |message| %>
            <ul>
              <li><%= message %></li>
            </ul>
          <% end %>
        <% end %>
      </div>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class:"form-control name" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, class:"form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class:"form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container px-5 px-sm-0">
   <div class="row">
      <h2>Followers Users</h2>
    <% if @users.present? %>
       <table class="table">
         <thead>
           <tr>
             <th>image</th>
             <th>name</th>
             <th colspan="3"></th>
             <th colspan="3"></th>
             <th colspan="3"></th>
           </tr>
         </thead>
         <tbody>
             <% @users.each do |user| %>
              <tr>
                 <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no-image.png",size:'40x40', class:"attachment user profile_image fallback" %></td>               <td>p</td>
                 <td><%= user.name %></td>
                 <td><p>フォロー数:<%= user.followings.count %></p></td>
                 <td> <p>フォロワー数:<%= user.followers.count %></p></td>
                 <td><%= link_to"Show", user_path(user) %></td>
               </tr>
             <% end %>
         </tbody>
       </table>
    <% else %>
      <table class="table table-borderless">
        <tr>
           <td><p>ユーザがいません</p></td>
        </tr>
      </table>
    <% end %>
   </div>
</div>

app/views/users/followings.html.erb
<div class="container px-5 px-sm-0">
   <div class="row">
      <h2>Follows Users</h2>
      <% if @users.present? %>
        <table class="table">
           <thead>
             <tr>
               <th>image</th>
               <th>name</th>
               <th colspan="3"></th>
               <th colspan="3"></th>
               <th colspan="3"></th>
             </tr>
           </thead>
           <tbody>

               <% @users.each do |user| %>
                <tr>
                   <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no-image.png",size:'40x40', class:"attachment user profile_image fallback" %></td>               <td>p</td>
                   <td><%= user.name %></td>
                   <td><p>フォロー数:<%= user.followings.count %></p></td>
                   <td> <p>フォロワー数:<%= user.followers.count %></p></td>
                   <td><%= link_to"Show", user_path(user) %></td>
                 </tr>
               <% end %>
           </tbody>
       </table>
      <% else %>
      <table class="table table-borderless">
        <tr>
           <td><p>ユーザがいません</p></td>
        </tr>
      </table>
      <% end %>
   </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'searches/form' %>
    </div>
  </div>
</div>
<main>
  <div class="container px-5 px-sm-0">
    <div id="error_explanation" class="text-danger">
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>
    </div>
  <div class="row">
    <div class="col-md-3">
       <h2>User info</h2>
          <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no-image.png",size:'100x100', class:"attachment user profile_image fallback" %>
          <table class="table">
            <tbody>
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= current_user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= current_user.introduction %></th>
              </tr>
              <tr>
                <th>follows</th>
                <th><%= link_to @user.followings.count,followings_user_path(@user) %></th>
              </tr>
              <tr>
                <th>follower</th>
                <th><%= link_to @user.followers.count,followers_user_path(@user) %></th>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block", method: :get do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
        <h2 class="mt-3">New book</h2>
          <%= form_with model:@book,local:true do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title, class:"form-control book_title" %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Option</label>
              <%= f.text_area :body,class:"form-control book_body" %>
            </div>
            <div class="form-group">
              <%= f.submit "Create Book",class:"btn btn-success" %>
            </div>
          <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
       <table class="table">
         <thead>
           <tr>
             <th>image</th>
             <th>name</th>
             <th colspan="3"></th>
             <th colspan="3"></th>
             <th colspan="3"></th>
             <th colspan="3"></th>
           </tr>
         </thead>
         <tbody>
           <% @users.each do |user| %>
            <tr>
               <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no-image.png",size:'40x40', class:"attachment user profile_image fallback" %></td>               <td>p</td>
               <td><%= user.name %></td>
               <td>
                 <p>フォロー数</p>
               </td>
               <td>
                 <p>フォロワー数</p>
               </td>
               <td>
                 <% if current_user.is_followed_by?(user) %>
                     <%= link_to user_relationships_path(user), method: :delete do %>
                         <p>フォロー外す</p>
                     <% end %>
                 <% else %>
                      <%= link_to user_relationships_path(user), method: :post do %>
                         <p>フォローする</p>
                     <% end %>
                <% end %>
               </td>
               <td><%= link_to"Show", user_path(user) %></td>
             </tr>
           <% end %>
         </tbody>
       </table>
    </div>
  </div>
</div>
</main>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', user: @user %>
      <h2 class="mt-3">New book</h2>
        <%= form_with model:@book,local:true do |f| %>
        
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control book_title" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Option</label>
            <%= f.text_area :body,class:"form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit "Create Book",class:"btn btn-success" %>
          </div>
        <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Option</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @user.books.each do |book| %>
          <tbody>
            <tr>
                <td>
                  <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no-image.png", size:'40x40', class:"attachment user profile_image fallback" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td>
                  <%= book.body %>
                </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>