config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  resources :users do
     resource :relationships, only: [:create, :destroy]
     get :followings, on: :member
     get :followers, on: :member
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/serch.rb
class Serch < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end
  def is_followed_by?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!,except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?
 
  def after_sign_in_path_for(resource)
   user_path(resource)
  end
 
  protected
  
 def configure_permitted_parameters
    added_attrs = [:user_name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @favorite = Favorite.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
    @book_comments = BookComment.new
    @comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
     render "edit"
    else
      redirect_to books_path
    end
  end

 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
 end

 def destroy
   book = Book.find(params[:id])
   book.destroy
   redirect_to books_path
 end

 private
 def book_params
   params.require(:book).permit(:title, :body)
 end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
def top
  
end

def about
end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

private
  def search_for(model,content,method)
    if model == 'user'
      if method == "forward_match"
        User.where("name LIKE?", "#{content}%")
      elsif method == "backward_match"
        User.where("name LIKE?", "#{content}%")
      elsif method == "perfect_match"
        User.where("#{content}")
      elsif method == "partial_match"
        User.where("name LIKE?", "%#{content}%")
      else
        User.all
      end
    elsif model == 'book'
      if method == "forward_match"
        Book.where("name LIKE?", "#{content}%")
      elsif method == "backward_match"
        Book.where("name LIKE?", "#{content}%")
      elsif method == "perfect_match"
        Book.where("#{content}")
      elsif method == "partial_match"
        Book.where("name LIKE?", "%#{content}%")
      else
        Book.all
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
   @users = User.all
   @book = Book.new
   @follower_users = User.where.not(id: current_user.id)
   @user = current_user
  end

  def show
   @user = User.find(params[:id])
   @book = Book.new
  end

  def edit
      @user = User.find(params[:id])
   if @user == current_user
      render "edit"
   else
      redirect_to user_path(current_user)
   end
  end

  def update
   @user = User.find(params[:id])
   if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
   else
    render :edit
   end
  end

  def followings
   user = User.find(params[:id])
   @users = user.followings
  end

  def followers
   user = User.find(params[:id])
   @users = user.followers
  end

  private
  def user_params
   params. require(:user) .permit(:name, :email, :profile_image, :introduction)
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
      
      <div class="row">
      <%= link_to"Log in", new_user_session_path,class: "btn btn-info btn-primary btn-block"  %>
      </div>
      <br/>
      <div class="row">
      <%= link_to"Sign Up", new_user_registration_path,class: "btn btn-success btn-primary btn-block"  %>
      </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_tag(search_path, method: :get) do %>
    <%= text_field_tag 'content' %>
    <%= select_tag 'model', options_for_select({"User" => "user", "Book" => "book"}) %>
    <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial", "前方一致" => "forward_match", "後方一致" => "backward_match" }) %>
    <%= submit_tag '検索' %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'searches/form' %>
    </div>
  </div>
</div>

<% if @model == 'user' %>
  <h3>Users serach for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% else @model == 'books' %>
  <h3>Books search for "<%= @content %>"</h3>
  <%= render 'books/index', books: @records %>
<% end %>

app/views/searches/serche.html.erb
<% if @model == 'user' %>
  <h3>Users serach for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% else @model == 'books' %>
  <h3>Books search for "<%= @content %>"</h3>
  <%= render 'books/index', books: @records %>
<% end %>