config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  resources :users do
     resource :relationships, only: [:create, :destroy]
     get :followings, on: :member
     get :followers, on: :member
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/serch.rb
class Serch < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end
  def is_followed_by?(user)
    followings.include?(user)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @favorite = Favorite.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
    @book_comments = BookComment.new
    @comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
     render "edit"
    else
      redirect_to books_path
    end
  end

 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
 end

 def destroy
   book = Book.find(params[:id])
   book.destroy
   redirect_to books_path
 end

 private
 def book_params
   params.require(:book).permit(:title, :body)
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
def top
  
end

def about
end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

private
  def search_for(model,content,method)
    if model == 'user'
      if method == "forward_match"
        User.where("name LIKE?", "#{content}%")
      elsif method == "backward_match"
        User.where("name LIKE?", "#{content}%")
      elsif method == "perfect_match"
        User.where("#{content}")
      elsif method == "partial_match"
        User.where("name LIKE?", "%#{content}%")
      else
        User.all
      end
    elsif model == 'book'
      if method == "forward_match"
        Book.where("name LIKE?", "#{content}%")
      elsif method == "backward_match"
        Book.where("name LIKE?", "#{content}%")
      elsif method == "perfect_match"
        Book.where("#{content}")
      elsif method == "partial_match"
        Book.where("name LIKE?", "%#{content}%")
      else
        Book.all
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
   @users = User.all
   @book = Book.new
   @follower_users = User.where.not(id: current_user.id)
   @user = current_user
  end

  def show
   @user = User.find(params[:id])
   @book = Book.new
  end

  def edit
      @user = User.find(params[:id])
   if @user == current_user
      render "edit"
   else
      redirect_to user_path(current_user)
   end
  end

  def update
   @user = User.find(params[:id])
   if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
   else
    render :edit
   end
  end

  def followings
   user = User.find(params[:id])
   @users = user.followings
  end

  def followers
   user = User.find(params[:id])
   @users = user.followers
  end

  private
  def user_params
   params. require(:user) .permit(:name, :email, :profile_image, :introduction)
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav ml-auto">
           <% if user_signed_in? %>
             <li><%= link_to"Home", user_path(current_user), class:"fas fa-home nav-link text-light" %></li>
             <li><%= link_to"Users", users_path, class:"fas fa-users nav-link text-light" %></li>
             <li><%= link_to"Books", books_path, class:"fas fa-book-open nav-link text-light" %></li>
             <li><%= link_to "logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %></li>
           <% else %>
             <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
             <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
             <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>
            <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>
           <% end %>
         </ul>
      </div>
      </div>
    </nav>
    
  </header>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <main class="mb-auto">
    <%= yield %>
  </main>
  <footer>
    <div class="contailer mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>

</html>